services:
  - docker

jobs:
  include:
    - stage: asmith
      script: docker build asmith/. -t shrysr/asmith:v1
    - stage: rbase
      script: docker build rbase/. -t shrysr/rbase:v2
    - stage: rstudio-and-shiny
      script: docker build rstudio/. -t shrysr/rstudio:v2
      script: docker build shiny/. -t shrysr/shiny:v2
