name: Docker Image CI

on:
  push:
    paths:
    - '/docs/*'
    - 'Readme.*'
    - '*.md'
    - '*.org'

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build Asmith
      run: docker build asmith/. --file asmith/Dockerfile --tag my-image-name:$(date +%s)
