name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build rbase
      run: docker build rbase/. --file rbase/Dockerfile --tag my-image-name:$(date +%s)
