name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: shrysr/sr-ds-docker/shiny/shiny@v2
    - name: shiny
      run:  docker build . --file shrysr/sr-ds-docker/shiny/Dockerfile --tag my-image-name:$(date +%s)
