name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build rstudio
      run: docker build rstudio/. --file rstudio/Dockerfile --tag my-image-name:$(date +%s)
